name: F3RVA Infrastructure Release

on: 
  push:
    tags: 
      - 'v*.*.*'

jobs:

  # create release
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout tag
        uses: actions/checkout@v3
        with:
          ref: '${{ env.tag }}'

      - name: Create version file
        run: |
          echo 'VERSION: ${{ env.tag }}' >> VERSION

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: 'release-${{ env.tag }}'
          body_path: 'CHANGELOG.md'
          draft: false
          prerelease: false
          generate_release_notes: true
          append_body: true
          files: |
            VERSION
