name: F3RVA Infrastructure Release

on: 
  push:
    tags: 
      - 'v*.*.*'

jobs:

  # create release
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        id: vars
        run: echo "{tag}=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Create version file
        run: |
          echo 'VERSION: ${{ steps.vars.outputs.tag }}' >> VERSION

      - name: Create release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          title: 'release-${{ steps.vars.outputs.tag }}'
          prerelease: false
          files: |
            LICENSE
            VERSION
            bin
            lib
            scripts
            test
            cdk.context.json
            cdk.json
            package-lock.json
            package.json
            tsconfig.json
