name: F3RVA Infrastructure Release

on: 
  push:
    tags: 
      - 'v*.*.*'

jobs:

  # create release
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - name: Set Variables
        id: vars
        run: echo "{tag}=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Checkout tag
        uses: actions/checkout@v2
        with:
          ref: '${{ steps.vars.outputs.tag }}'

      - name: Create version file
        run: |
          echo 'VERSION: ${{ steps.vars.outputs.tag }}' >> VERSION

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: 'release-${{ steps.vars.outputs.tag }}'
          body_path: 'CHANGELOG.md'
          draft: false
          prerelease: false
          generate_release_notes: true
          append_body: true
          files: |
            LICENSE
            VERSION
            bin
            lib
            scripts
            test
            cdk.context.json
            cdk.json
            package-lock.json
            package.json
            tsconfig.json
